"""
generate_animator — generate a C# Editor script that creates an AnimatorController
for the character with all imported animation clips wired up.

The generated script runs via: Tools > GGM > Create Animator for {CharacterName}
"""
import json


CS_TEMPLATE = '''\
// Auto-generated by GGM AnimationImporter — {character_name}
// Run via: Tools > GGM > Create Animator for {character_name}
using UnityEngine;
using UnityEditor;
using UnityEditor.Animations;

namespace GGM.Generated
{{
    public static class CreateAnimator_{safe_name}
    {{
        private const string CharacterName  = "{character_name}";
        private const string AnimationsPath = "{animations_path}";

        [MenuItem("Tools/GGM/Create Animator for {character_name}")]
        public static void CreateAnimatorController()
        {{
            // Create AnimatorController asset
            var controllerPath = $"{{AnimationsPath}}/{safe_name}_Animator.controller";
            var controller     = AnimatorController.CreateAnimatorControllerAtPath(controllerPath);

            // Add default layer parameters
            controller.AddParameter("Speed",      AnimatorControllerParameterType.Float);
            controller.AddParameter("IsGrounded", AnimatorControllerParameterType.Bool);
            controller.AddParameter("Attack",     AnimatorControllerParameterType.Trigger);
            controller.AddParameter("Die",        AnimatorControllerParameterType.Trigger);

            var rootStateMachine = controller.layers[0].stateMachine;

{state_setup}

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log($"[GGM] AnimatorController created at {{controllerPath}} with {clip_count} clips");
        }}
    }}
}}
'''

STATE_TEMPLATE = '''\
            // State: {anim_name}
            var state_{idx} = rootStateMachine.AddState("{anim_name}");
            var clip_{idx}  = AssetDatabase.LoadAssetAtPath<AnimationClip>($"{{AnimationsPath}}/{filename}");
            if (clip_{idx} != null) state_{idx}.motion = clip_{idx};
'''


def _indent(text: str, spaces: int) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line.strip() else "" for line in text.splitlines())


def run(ctx: dict) -> dict:
    inputs  = ctx["inputs"]
    outputs = ctx["outputs"]

    name              = inputs.get("name", "Character")
    generate_animator = inputs.get("generateAnimator", True)
    output_path       = inputs.get("outputPath", "Assets/Animations/Characters/").strip("/")
    imported_paths    = outputs.get("copy_fbx", {}).get("importedPaths", [])

    if not generate_animator:
        print("[generate_animator] Skipped — generateAnimator is false")
        return {"skipped": True}

    if not imported_paths:
        raise ValueError("No imported paths — copy_fbx step must run first")

    safe_name       = "".join(c for c in name if c.isalnum() or c == "_")
    animations_path = f"{output_path}/{name}"

    # Build state setup code
    state_lines = []
    for idx, clip_info in enumerate(imported_paths):
        state_lines.append(STATE_TEMPLATE.format(
            anim_name=clip_info["animName"],
            idx=idx,
            filename=clip_info["filename"],
        ))
    state_setup = "\n".join(state_lines)

    code = CS_TEMPLATE.format(
        character_name=name,
        safe_name=safe_name,
        animations_path=animations_path,
        state_setup=state_setup,
        clip_count=len(imported_paths),
    )

    print(f"[generate_animator] {len(imported_paths)} states in AnimatorController")
    return {"code": code, "statCount": len(imported_paths)}
