"""
generate_cs — convert the tile grid into a Unity C# Editor script
that programmatically populates a Tilemap component.

The generated script is a Unity MenuItem that the user runs once:
  Tools > GGM > Populate {LevelName}
"""
import json


CS_TEMPLATE = '''\
// Auto-generated by GGM TilemapPopulator — {level_name}
// Run via: Tools > GGM > Populate {level_name}
using UnityEngine;
using UnityEditor;
using UnityEngine.Tilemaps;

namespace GGM.Generated
{{
    public static class Populate_{safe_name}
    {{
        private const string TilemapObjectName = "{level_name}Tilemap";
        private const string TilesetPath       = "{tileset_path}";

        [MenuItem("Tools/GGM/Populate {level_name}")]
        public static void Populate()
        {{
            // Find or create Tilemap in scene
            var tmObj = GameObject.Find(TilemapObjectName);
            if (tmObj == null)
            {{
                var grid = new GameObject(TilemapObjectName);
                grid.AddComponent<Grid>();
                tmObj = new GameObject("Tilemap");
                tmObj.transform.SetParent(grid.transform);
                tmObj.AddComponent<Tilemap>();
                tmObj.AddComponent<TilemapRenderer>();
            }}
            var tilemap = tmObj.GetComponent<Tilemap>();
            tilemap.ClearAllTiles();

            // Tile lookup — load tiles by name from tileset path
{tile_loads}

            // Layout
{placements}

            EditorUtility.SetDirty(tilemap);
            Debug.Log("[GGM] {level_name} tilemap populated — {total_tiles} tiles");
        }}
    }}
}}
'''


def _indent(text: str, spaces: int) -> str:
    pad = " " * spaces
    return "\n".join(pad + line for line in text.splitlines())


def run(ctx: dict) -> dict:
    inputs  = ctx["inputs"]
    outputs = ctx["outputs"]

    name         = inputs.get("name", "Level")
    tileset_path = inputs.get("tilesetPath", "Assets/Tiles/") or "Assets/Tiles/"
    layout_out   = outputs.get("generate_layout", {})
    grid         = layout_out.get("grid", [])
    tile_vocab   = layout_out.get("tileVocab", ["Floor", "Wall"])

    safe_name   = "".join(c for c in name if c.isalnum() or c == "_")
    total_tiles = sum(1 for row in grid for cell in row if cell)

    # Tile variable loads
    tile_var_lines = []
    for tile in tile_vocab:
        var_name = tile[0].lower() + tile[1:] + "Tile"
        tile_var_lines.append(
            f'var {var_name} = AssetDatabase.LoadAssetAtPath<TileBase>($"{{TilesetPath}}{tile}.asset");'
        )
    tile_loads = _indent("\n".join(tile_var_lines), 12)

    # Tile placements
    placement_lines = []
    for y, row in enumerate(grid):
        for x, tile_name in enumerate(row):
            if not tile_name:
                continue
            # Unity tilemap Y is bottom-up; flip row index
            unity_y = len(grid) - 1 - y
            var_name = tile_name[0].lower() + tile_name[1:] + "Tile"
            placement_lines.append(
                f"tilemap.SetTile(new Vector3Int({x}, {unity_y}, 0), {var_name});"
            )
    placements = _indent("\n".join(placement_lines), 12)

    code = CS_TEMPLATE.format(
        level_name=name,
        safe_name=safe_name,
        tileset_path=tileset_path.rstrip("/") + "/",
        tile_loads=tile_loads,
        placements=placements,
        total_tiles=total_tiles,
    )

    print(f"[generate_cs] {total_tiles} SetTile calls, {len(tile_vocab)} tile types")
    return {"code": code, "tileCount": total_tiles}
